import { defineConfig } from '../shared/define';

export default defineConfig({
  meta: {
    name: {
      '': '中间页自动跳转',
      'zh-CN': '中间页自动跳转',
      en: 'Auto Redirect — Skip intermediate link pages',
    },
    namespace: 'https://github.com/XiaoLinXiaoZhu/JavaScriptTools',
    version: '0.1.0',
    description: {
      '': '自动跳过 CSDN、知乎、豆瓣、微博、简书、Gitee、掘金等 30+ 网站的中间确认页，直接跳转到目标链接。',
      en: 'Automatically skip intermediate confirmation pages on 30+ Chinese websites (CSDN, Zhihu, Weibo, Juejin, etc.) and redirect directly to the target URL.',
    },
    author: 'XLXZ',
    match: [
      '*://link.csdn.net/*',
      '*://link.zhihu.com/*',
      '*://www.jianshu.com/go-wild*',
      '*://gitee.com/link*',
      '*://juejin.cn/*target*',
      '*://weibo.cn/sinaurl*',
      '*://support.qq.com/products/*/link-jump*',
      '*://oschina.net/action/GoToLink*',
      '*://afdian.net/link*',
      '*://jump.bdimg.com/safecheck*',
      '*://jump2.bdimg.com/safecheck*',
      '*://www.douban.com/link2/*',
      '*://link.17173.com/*',
      '*://docs.qq.com/scenario/link*',
      '*://mail.qq.com/cgi-bin/readtemplate*',
      '*://wx.mail.qq.com/xmspamcheck/xmsafejump*',
      '*://c.pc.qq.com/middlem*',
      '*://c.pc.qq.com/ios*',
      '*://sspai.com/link*',
      '*://nodeseek.com/jump*',
      '*://kdocs.cn/office/link*',
      '*://www.kdocs.cn/office/link*',
      '*://cloud.tencent.com/developer/tools/blog-entry*',
      '*://link.uisdc.com/*',
      '*://www.yuque.com/r/goto*',
      '*://blog.51cto.com/transfer*',
      '*://r.wjx.com/redirect.aspx*',
      '*://www.infoq.cn/link*',
      '*://open.work.weixin.qq.com/wwopen/uriconfirm*',
      '*://link.gitcode.com/*',
      '*://n.dingtalk.com/dingding/h5-url-verification*',
      '*://weboffice.qq.com/scenario/link.html*',
    ],
    grant: ['GM_getValue', 'GM_setValue', 'GM_registerMenuCommand'],
    license: 'MIT',
    icon: 'https://www.google.com/s2/favicons?domain=csdn.net',
  },
  category: 'navigation',
  greasyforkId: undefined,
});
